src/locales/english.json
change the name from "Golden Shell" to "Gold Shell"
=> Change shell naming

src/components/Header/index.tsx, src/components/OttoCard.tsx, src/models/Otto.ts, src/pages/leaderboard/RankList/index.tsx, src/pages/my-items/use-item/OttoList.tsx, src/pages/otto/OttoPage/index.tsx, src/utils/image.ts
no need to let user download high resolution images
=> pref: crop images

src/hooks/useMyItems.ts, src/pages/my-items/MyItemsPage.tsx
https://github.com/apollographql/react-apollo/issues/3709
=> fix: fix the issue of loading items

public/locales/en/common.json, src/components/ChartTooltip.tsx, src/components/Switcher.tsx, src/components/TreasuryRevenuesChart.tsx, src/contexts/Currency.tsx, src/views/treasury-dashboard/index.tsx
=> Staked CLAM Chart Headers

otter-graphql-schema.json, src/components/TreasuryMarketValueChart.tsx, src/graphs/__generated__/GetTreasuryMetrics.ts, src/graphs/__generated__/LastPayout.ts, src/graphs/otter.ts
Adds the stMATIC/USD+ pair to the assets chart
=> Stmatic pair

otter-graphql-schema.json, src/components/TreasuryMarketValueChart.tsx, src/components/TreasuryRevenuesChart.tsx, src/graphs/__generated__/GetTreasuryMetrics.ts, src/graphs/__generated__/GetTreasuryRevenue.ts, src/graphs/otter.ts
Front-end for MAI-stMATIC [Task](https://app.asana.com/0/1202610130288819/1202835279013198)
=> Add MAI-stMATIC asset and Lido revenue

public/locales/en/common.json, public/locales/zh-cn/common.json, public/locales/zh-tw/common.json, src/models/Item.ts, src/views/my-items/MyItemsPage.tsx
1. Split sort into property and order
2. Change filters from otto-specific to otto-equippable and same for lottie, finding it to be a much more useful filter. Maybe we can add both kinds, not sure.
=> Adding sort features

public/locales/en/common.json, public/locales/zh-cn/common.json, public/locales/zh-tw/common.json, src/views/my-items/MyItemsPage.tsx
Also fixes weird duplicate item issue by removing duplicate keys.
=> Add sort by theme boost

src/components/TreasuryMarketValueChart.tsx
=> Fix merge issue with  chart

src/components/ItemCell/index.tsx
=> feat: show tooltip when users hover over otto images

.env, otter-graphql-schema.json, otto-graphql-schema.json, package.json, src/components/TreasuryMarketValueChart.tsx, src/graphs/__generated__/GetTreasuryMetrics.ts, src/graphs/otter.ts
@0xthk breaking change, please merge immediately AFTER the back-end PR.
=> Mai migration

src/components/AssetsLoader/index.tsx, src/hooks/useEstimatedReward.ts, src/views/leaderboard/RankList/index.tsx
- [Leaderboard] Add a subtotal of my estimated rewards on the top of my Ottos list : https://app.asana.com/0/1202495225628073/1203531010251732
- [Leaderboard] Fix my Otto ranking on Adventure Leaderboard : https://app.asana.com/0/1202495225628073/1203531010251738
- Loading info tooltips - change font to match app : https://app.asana.com/0/1202495225628073/1202796442282373
=> Leaderboard UI improvements

otter-graphql-schema.json, package.json, snapshot-graphql-schema.json, src/components/TreasuryMarketValueChart.tsx, src/graphs/__generated__/GetTreasuryMetrics.ts, src/graphs/otter.ts, src/hooks/useCrossChainTreasuryMetrics.ts, src/views/treasury-dashboard/index.tsx, src/views/treasury-investments/index.tsx
- Moves Cross-Chain metrics into a hook, so it can be reused on both Dashboard and Investments page
- Adds Arrakis MAI/USDC to Dashboard chart (+untracked $value in investments page, will aggregate AVAX investments next)
=> Investments page avax

src/views/mine/index.tsx
=> fix: mine page styles

src/components/AdventurePopup/ResultStep/index.tsx
Changed the logic slightly, this one is bulletproof.
=> Fix button showing for non ready otters

src/components/ItemFilterSelect/index.tsx
1. Add clear button for search
2. fix filter box alignment
3. round corner for shading
=> Additional My Items Tweaks

src/components/Help/index.tsx, src/components/ItemCell/index.tsx
The link doesn't really behave as expected (esp when using multi-equip).
=> fix tooltip cutoff, remove linkability of thumbnail

src/App.tsx
add multicallVersion to match polygon stored address, prevents spurious failing aggregate requests
=> Fix spurious aggregate(0x) calls

src/components/Help/index.tsx
This reverts commit 7f9abbc462a13192a1f77d9fe29851696d46508e.
The commit break the build @eonwarped
=> Revert "Use createPortal to pop out otto tooltip (#413)"

public/locales/en/common.json, public/locales/zh-cn/common.json, public/locales/zh-tw/common.json, src/components/OttoPopup/Body.tsx, src/contexts/ItemFilters.tsx
Looks at unequipped items for the best and compare with native. Prefers higher theme boost.
=> Add Rarity Ottomize button

src/contracts/functions.ts, src/libs/api.ts, src/views/foundry/ForgeItem.tsx, src/views/store/BuyFishItemPopup.tsx, src/views/store/FishProductCard.tsx
Uses new API parameters to allow multiple for a buy or fuse. 
Screenshots:
Desktop shop and foundry
Mobile shop and foundry
=> Buy multiple items and fuse multiple amounts of a formula

src/views/foundry/ForgeItem.tsx
This reverts commit f68a8530075dc6c08b30b0f78af2359e8e1800cf.
=> Re-enable multi-fuse now that contract is updated

src/contexts/RarityEpoch.tsx, src/hooks/useEstimatedReward.ts
Affects both the rarity and adventure leaderboards.
Ambassotter voted unanimously to go for the change, with support from Core Team.
=> Add flattened reward curve to epoch 23 and above

src/components/WalletSelector/index.tsx, src/hooks/useContractAddresses.ts
Now it will not pop up 'wrong chain id', and it will auto-login on refresh.
=> Mitigate metamask eager connect issue

src/components/AdventurePopup/ResultStep/RewardSection.tsx
Allow wrapping to show all retrieved items.
=> Fix display for multiple items

src/components/AdventurePopup/ExploringStep/index.tsx, src/contracts/functions.ts
- Max stake round detection fixed
- Show error when buy chest fails
=> Minor Bug Fixes
